name: aws-vault

on:
  workflow_dispatch: {}
  schedule:
    - cron: '55 12 * * *'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: ./packages/aws-vault.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
