name: bitwarden-cli

on:
  workflow_dispatch: {}
  schedule:
    - cron: '43 11 * * *'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: ./packages/bitwarden-cli.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_NOTIF_ISSUE_NUMBER: 2
          GITHUB_NOTIF_ISSUE_TOKEN: ${{ secrets.GH_NOTIF_ISSUE_TOKEN }}
