name: buildpacks-pack

on:
  workflow_dispatch: {}
  schedule:
    - cron: '41 2 * * *'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: ./packages/buildpacks-pack.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
