name: docker-credential-secretservice

on:
  workflow_dispatch: {}
  schedule:
    - cron: '18 15 * * *'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: ./packages/docker-credential-secretservice.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
